model_name_or_path: Qwen/Qwen2.5-Coder-14B-Instruct
template: qwen
trust_remote_code: true
stage: sft
do_train: true
do_eval: false
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all
dataset: all_mix_train_repair
dataset_dir: data
cutoff_len: 2048
packing: false
train_on_prompt: false
mask_history: false
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 32
output_dir: outputs/mix_lora
logging_steps: 5
save_steps: 300
plot_loss: true
overwrite_output_dir: false
save_only_model: false
report_to: none
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
fp16: false
ddp_timeout: 180000000
seed: 42
optim: adamw_torch_fused
weight_decay: 0.0
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
max_grad_norm: 1.0
eval_strategy: 'no'
disable_gradient_checkpointing: false
